<!DOCTYPE html>
<html>
<head>
  <title>Second Song</title>
  <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>

<?php
echo "<div class='container'>";

    echo "<h1>Traitor by Olivia Rodrigo</h1>";
echo "\n";
echo "\n";
echo "<pre>";
    echo "[Verse 1]";
echo "\n";
    echo " C                      Em";
echo "\n";
    echo "Brown guilty eyes and little white lies";
echo "\n";
    echo "         Am                      Fmaj7";
echo "\n";
    echo "Yeah, I played dumb but I always knew";
echo "\n";
    echo "      C                     Em";
echo "\n";
    echo "That you talk to her, maybe did even worse";
echo "\n";
    echo "C        Am                   Fmaj7";
echo "\n";
    echo "I kept quiet so I could keep you";
echo "\n";
echo "\n";
    echo "[Pre-Chorus]";
echo "\n";
    echo "               C";
echo "\n";
    echo "And ain't it funny";
echo "\n";
    echo "        Em";
echo "\n";
    echo "How you ran to her";
echo "\n";
    echo "      Am                     Fmaj7";
echo "\n";
    echo "The second that we called it quits";
echo "\n";
    echo "               C";
echo "\n";
    echo "And ain't it funny";
echo "\n";    
    echo "         Em";
echo "\n";    
    echo "How you said you were friends";
echo "\n";    
    echo "        Am                     Fmaj7";
echo "\n";    
    echo "Now it sure as hell don't look like it";
echo "\n";    
echo "\n";
    echo "[Chorus]";
echo "\n";    
    echo "      C";
echo "\n";    
    echo "You betrayed me";
echo "\n";    
    echo "   Em                              Am";
echo "\n";
    echo "And I know that you'll never feel sorry";
echo "\n";
    echo "   Fmaj7";
echo "\n";
    echo "For the way I hurt, yeah"; 
echo "\n";
    echo " C";
echo "\n";
    echo "You talked to her";
echo "\n";
    echo " When we were together";
echo "\n";
    echo "      Am";
echo "\n"; 
    echo "Loved you at your worst";
echo "\n";
    echo "    Fmaj7";
echo "\n";    
    echo "But that didn't matter";
echo "\n";    
    echo "    C";
echo "\n";    
    echo "It took you two weeks";
echo "\n";    
    echo "   Em";
echo "\n";    
    echo "To go off and date her";
echo "\n";    
    echo "      Am";
echo "\n";    
    echo "Guess you didn't cheat";
echo "\n";    
    echo "    N.C.";
echo "\n";    
    echo "But you're still a traitor";
echo "\n";    
echo "\n";
    echo "[Verse 2]";
echo "\n";    
    echo "C"; 
echo "\n"; 
    echo "Now you bring her around";
echo "\n";    
    echo "     Em";
echo "\n";    
    echo "Just to shut me down";
echo "\n";    
    echo "         Am                   Fmaj7";
echo "\n";    
    echo "Show her off like she's a new trophy";
echo "\n";    
    echo "           C";
echo "\n";    
    echo "And I know if you were true";
echo "\n";    
    echo "            Em";
echo "\n";    
    echo "There's no damn way that you";
echo "\n";    
    echo "               Am                      Fmaj7";
echo "\n";    
    echo "Could fall in love with somebody that quickly";
echo "\n";    
echo "\n";
    echo "[Pre-Chorus]";
echo "\n";    
    echo "          C";
echo "\n"; 
    echo "Ain't it funny";
echo "\n";    
    echo "    Em";
echo "\n";    
    echo "All the twisted games";
echo "\n";    
    echo "          Am                   Fmaj7";
echo "\n";  
    echo "All the questions you used to avoid?";
echo "\n";   
    echo "           C";
echo "\n";   
    echo "Ain't it funny?";
echo "\n";   
    echo "         Em";
echo "\n";  
    echo "Remember I brought her up";
echo "\n";   
    echo "         Am            Fmaj7";
echo "\n";    
    echo "And you told me I was paranoid";
echo "\n";  
echo "\n";  
    echo "[Chorus]";
echo "\n";    
    echo "      C";
echo "\n";    
    echo "You betrayed me";
echo "\n";    
    echo "    Em                             Am";
echo "\n";    
    echo "And I know that you'll never feel sorry";
echo "\n"; 
    echo "   Fmaj7";
echo "\n";    
    echo "For the way I hurt, yeah";
echo "\n";    
    echo " C";
echo "\n";    
    echo "You talked to her";
echo "\n";    
    echo "     Em";
echo "\n";    
    echo "When we were together";
echo "\n";    
    echo "      Am";
echo "\n";    
    echo "Loved you at your worst";
echo "\n";    
    echo "    Fmaj7";
echo "\n";    
    echo "But that didn't matter";
echo "\n";    
    echo "    C";
echo "\n";    
    echo "It took you two weeks";
echo "\n";  
    echo "   Em";
echo "\n";    
    echo "To go off and date her";
echo "\n";    
    echo "       Am";
echo "\n";    
    echo "Guess you didn't cheat";
echo "\n"; 
    echo "N.C.";
echo "\n";    
    echo "But you're still a traitor";
echo "\n";    
echo "\n";
    echo "[Bridge]";
echo "\n";    
    echo "C     Em          Am";
echo "\n";    
    echo " (Ah, ah, ah, ah) God, I wish that you had thought this through";
echo "\n";    
    echo "Fmaj7";
echo "\n";    
    echo "Before I went and fell in love with you";
echo "\n";    
    echo "C     Em                        Am";
echo "\n";    
    echo " (Ah, ah, ah, ah)  When she's sleeping in the bed we made";
echo "\n";    
    echo "          Fmaj7";
echo "\n";    
    echo "Don't you dare forget about the way";
echo "\n"; 
echo "\n";   
    echo "[Chorus]";
echo "\n";    
    echo "      C";
echo "\n"; 
    echo "You betrayed me";
echo "\n";    
    echo "    Em                             Am";
echo "\n";    
    echo "Cuz I know that you'll never feel sorry";
echo "\n";    
    echo "   Fmaj7";
echo "\n";    
    echo "For the way I hurt, yeah";
echo "\n";    
    echo " C";
echo "\n";    
    echo "You talked to her";
echo "\n";    
    echo "     Em";
echo "\n";  
    echo "When we were together";
echo "\n";   
    echo "     Am";
echo "\n";   
    echo "You gave me your word";
echo "\n";   
    echo "    Fmaj7";
echo "\n";   
    echo "But that didn't matter";
echo "\n";  
    echo "    C";
echo "\n";   
    echo "It took you two weeks";
echo "\n";   
    echo "   Em";
echo "\n";   
    echo "To go off and date her";
echo "\n";    
    echo "      Am";
echo "\n";    
    echo "Guess you didn't cheat";
echo "\n";    
    echo "    Fmaj7                        C  Em Am";
echo "\n"; 
    echo "But you're still, you're still a traitor (Ah, ah, ah, ah)";
echo "\n";    
    echo "      Fmaj7";
echo "\n";    
    echo "Yeah, you're still a traitor";
echo "\n";    
echo "\n";
    echo "[Outro]";
echo "\n";    
    echo "C    Em      Am";
echo "\n";    
    echo " Oh, oh, oh God, I wish that you had thought this through";
echo "\n";    
    echo " Fm";
echo "\n";    
    echo "before I went and fell in love with you";

echo "</div>";
?>

</body>
</html>