<!DOCTYPE html>
<html>
<head>
  <title>First Song</title>
  <link rel="stylesheet" type="text/css" href="style.css"> 
</head>

<body>

<?php



echo "<div class='container'>";
        
    echo "<h1>Enchanted by Taylor Swift</h1>";
echo "\n";
echo "\n";
echo "<pre>";
    echo "[Intro]";
echo "\n";
    echo "G   Bm   C   G";
echo "\n";
    echo "[Verse 1]";
echo "\n";
    echo "G";
echo "\n";
    echo "There I was again tonight";
echo "\n";
    echo "Bm";
echo "\n";
    echo "Forcing laughter, faking smiles";
echo "\n";
    echo "C                         G";
echo "\n";
    echo "Same old tired, lonely place";
echo "\n";
    echo "G";
echo "\n";
    echo "Walls of insincerity";
echo "\n";
    echo "Bm";
echo "\n";
    echo "Shifting eyes and vacancy";
echo "\n";
    echo "C                          G";
echo "\n";
    echo "Vanished when I saw your face";
echo "\n";
echo "\n";
    echo "                     C                   Em   D";
echo "\n";
    echo "All I can say is, it was enchanting to meet you";
echo "\n";
echo "\n"; 
    echo "[Verse 2]";
echo "\n";
    echo "G";
echo "\n";    
    echo "Your eyes whispered 'have we met?'";
echo "\n";    
    echo "Bm";
echo "\n";    
    echo "Crossed the room, your silhouette";
echo "\n";    
    echo "C                          G";
echo "\n";    
    echo "Starts to make its way to me";
echo "\n";    
    echo "    G";
echo "\n";    
    echo "The playful conversation starts";
echo "\n";    
    echo "Bm";
echo "\n";
    echo "Counter all your quick remarks";
echo "\n";
    echo "    C                       G";
echo "\n";
    echo "Like passing notes in secrecy"; 
echo "\n";
    echo "       C                   Em   D";
echo "\n";
    echo "And it was enchanting to meet you";
echo "\n";
    echo "                    C                  Em   D";
echo "\n";
    echo "All I can say is, I was enchanted to meet you";
echo "\n"; 
echo "\n"; 
    echo "[Chorus]";
echo "\n";
    echo "C               G";
echo "\n";    
    echo "  This night is sparkling";
echo "\n";    
    echo "D                C";
echo "\n";    
    echo "Don't you let it go";
echo "\n";    
    echo "            G";
echo "\n";    
    echo "I'm wonderstruck";
echo "\n";    
    echo "         D             C";
echo "\n";    
    echo "Blushing all the way home";
echo "\n";    
    echo "              G    D                C";
echo "\n";    
    echo "I'll spend forever wondering if you knew";
echo "\n";    
    echo "                     Em     D  G";
echo "\n";    
    echo "I was enchanted to meet you-ou-ou";
echo "\n"; 
echo "\n"; 
    echo "[Verse 3]";
echo "\n";    
    echo "    G";
echo "\n";    
    echo "The lingering question kept me up";
echo "\n";    
    echo "Bm";
echo "\n";    
    echo "2 AM, who do you love?";
echo "\n";    
    echo " C                       G";
echo "\n";    
    echo "I wonder till I'm wide awake";
echo "\n";    
    echo "    G";
echo "\n";    
    echo "And now I'm pacing back and forth";
echo "\n";    
    echo "Bm";
echo "\n";    
    echo "Wishing you were at my door";
echo "\n";    
    echo "  C                         G";
echo "\n";    
    echo "I'd open up and you would say 'hey'";
echo "\n"; 
    echo "   C                   Em   D";
echo "\n";    
    echo "It was enchanting to meet you";
echo "\n";    
    echo "                C                  Em   D";
echo "\n";    
    echo "All I know is I was enchanted to meet you";
echo "\n"; 
echo "\n"; 
    echo "[Chorus]";
echo "\n";   
    echo "C               G";
echo "\n";   
    echo "This night is sparkling";
echo "\n";   
    echo "D                C";
echo "\n";  
    echo "Don't you let it go";
echo "\n";   
    echo "        G";
echo "\n";    
    echo "I'm wonderstruck";
echo "\n";    
    echo "     D             C";
echo "\n";    
    echo "Blushing all the way home";
echo "\n";    
    echo "          G    D                C";
echo "\n";    
    echo "I'll spend forever wondering if you knew";
echo "\n";    
    echo "C  Em  D";
echo "\n"; 
    echo "C               G";
echo "\n";    
    echo "This night is flawless";
echo "\n";    
    echo "D                C";
echo "\n";    
    echo "Don't you let it go";
echo "\n";    
    echo "           G";
echo "\n";    
    echo "I'm wonderstruck";
echo "\n";    
    echo "         D            C";
echo "\n";    
    echo "Dancing around all alone";
echo "\n";    
    echo "              G    D                C";
echo "\n";    
    echo "I'll spend forever wondering if you knew";
echo "\n";    
    echo "                     Em   D";
echo "\n";    
    echo "I was enchanted to meet you";
echo "\n"; 
echo "\n"; 
    echo "[Instrumental]";
echo "\n";    
    echo "G   Bm   C   G";
echo "\n";    
    echo "G   Bm   C   D";
echo "\n";    
    echo "This is me praying that";
echo "\n"; 
echo "\n"; 
    echo "[Bridge]";
echo "\n";    
    echo "C";
echo "\n";    
    echo "This was the very first page";
echo "\n";    
    echo "Em              D";
echo "\n";    
    echo "Not where the storyline ends";
echo "\n";    
    echo "C";
echo "\n";    
    echo "My thoughts will echo your name";
echo "\n";    
    echo "Em        D";
echo "\n";    
    echo "Until I see you again";
echo "\n";    
    echo "C                                Em        D";
echo "\n";    
    echo "These are the words I held back as I was leaving too soon";
echo "\n";    
    echo "C                      Em   Dadd4/F#";
echo "\n";    
    echo "I was enchanted to meet you";
echo "\n"; 
    echo "G                             Bm";
echo "\n";    
    echo "Please, don't be in love with someone else";
echo "\n";    
    echo "C                           G";
echo "\n";    
    echo "Please, don't have somebody waiting on you";
echo "\n";    
    echo "G                             Bm";
echo "\n";    
    echo "Please, don't be in love with someone else";
echo "\n";    
    echo "C                           G";
echo "\n";    
    echo "Please, don't have somebody waiting on you";
echo "\n"; 
echo "\n"; 
    echo "[Chorus]";
echo "\n";   
    echo "C               G";
echo "\n";   
    echo "This night is sparkling";
echo "\n";   
    echo "D                C";
echo "\n";   
    echo "Don't you let it go";
echo "\n";  
    echo "            G";
echo "\n";   
    echo "I'm wonderstruck";
echo "\n";   
    echo "         D             C";
echo "\n";   
    echo "Blushing all the way home";
echo "\n";    
    echo "              G    D                C";
echo "\n";    
    echo "I'll spend forever wondering if you knew";
echo "\n";    
    echo "C  Em  D";
echo "\n"; 
    echo "C               G";
echo "\n";    
    echo "This night is flawless";
echo "\n";    
    echo "D                C";
echo "\n";    
    echo "Don't you let it go";
echo "\n";    
    echo "            G";
echo "\n";    
    echo "I'm wonderstruck";
echo "\n";    
    echo "         D            C";
echo "\n";    
    echo "Dancing around all alone";
echo "\n";    
    echo "              G    D                C";
echo "\n";    
    echo "I'll spend forever wondering if you knew";
echo "\n";    
    echo "                     Em   D";
echo "\n";    
    echo "I was enchanted to meet you";
echo "\n"; 
echo "\n"; 
    echo "[Outro]";
echo "\n";    
    echo "G                             Bm";
echo "\n";   
    echo "Please, don't be in love with someone else";
echo "\n";   
    echo "C                           G";
echo "\n";   
    echo "Please, don't have somebody waiting on you";

echo "</div>";
?>

</body>
</html>